version: "3.9"

services:
  backend:
    image: asia-south11111111-docker.pkg.dev/test-project-1-666666666/backend/backend:65
    container_name: django_backend_container
    command: >
      sh -c "sleep 10 &&
             python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn backend_rnd.wsgi:application --bind 0.0.0.0:8000 --timeout 5 --threads 10"

  frontend:
    image: asia-south11111111-docker.pkg.dev/test-project-1-4902166666666/frontend/frontend:65
    container_name: react_frontend_container
    depends_on:
      - backend
    command: >
      sh -c "sleep 15 && nginx -g 'daemon off;'"

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    command: >
      sh -c "sleep 20 && nginx -g 'daemon off;'"